### ISSUE TITLE
RocketMQSource 可以注册, 但没有消费消息

### ISSUE THREAD

**Issue by SKYhuangjing** [deemogsw/rocketMQ-flink-connector#1]
环境 : 阿里云 RocketMQ 4.x 版本
用法 : 使用 例子中的代码, 可以在 flink 上 跑起来, 但没有拉消息
备注 : 因为不太懂 flink 源代码, 所以撤回到了 官方的写法, 可以拉消息了

**Comment by SKYhuangjing** [comment]
> 环境 : 阿里云 RocketMQ 4.x 版本 用法 : 使用 例子中的代码, 可以在 flink 上 跑起来, 但没有拉消息 备注 : 因为不太懂 flink 源代码, 所以撤回到了 官方的写法, 可以拉消息了

最终本地测试通过

基于 Source Example, 添加了 commitOffsetAuto = true 且 移除了 checkpoint 设置
同时在 Builder 中添加了 AccessChannel 的设置, 这部分有 fork 作者的代码进行改造, 作者有兴趣可以看看, 是否需要我合并

**Comment by deemogsw** [comment]
我之前用4.x的镜像测试过RocketMQSource是ok的，我们目前线上用的3.X版本。checkpoint设置肯定是不能去除的，生产环境除非每次消费最新数据外，没有任务不配置检查点的。有生产使用需求可以再沟通一下问题，感觉是其他配置的问题

**Comment by SKYhuangjing** [comment]
那对于 commitOffsetAuto 这个设置, 有必要吗, 我看代码里面注释写的是 如果关闭 checkpoint, 则需要设置 commitOffsetAuto, 这两个设置冲突吗?

**Comment by deemogsw** [comment]
不能算冲突。打开checkpoint后 提交消费位点默认是在执行检查点过程中完成的。这样设计的好处是保证检查点保存的offset和服务器上保存的是一致的，并且在高峰期消费的时候避免了每条消息都做一次提交操作。如果关闭了检查点就需要设置commitOffsetAuto=true,这样每消费一条数据就会向服务端提交最新消费位置，这样会降低消息吞吐。如果关闭检查点并且commitOffsetAuto=false,就永远不会向服务端提交offset

**Comment by SKYhuangjing** [comment]
> 在高峰期消费的时候避免了每条消息都做一次提交操作。如果关闭了检查点就需要设置commitOffsetAuto=true,这样

感谢大佬解释, 理解了, 那我开启 checkpoint && 关闭 commitOffsetAuto 测试下.
